### ISSUE TITLE
Pre-1.3 Doc Review

### ISSUE THREAD

**Issue by CatGarab** [kubos/kubos#101]
It's everyone's favorite time of year: Doc Time... :sob: 

Doc Catchup:
- Update all the changelogs
Index
- Add info about viewing latest version of the docs at docs.kubos.co/master/{version}
	- Potentially, fix that so you can just go to docs.kubos.co/master/

KubOS Architecture
- Update communication service to link to communication service page (also, write communication service page)
- Mention UDP?

Kubos SDK
- Example projects
	- We have more example projects (UDP client, python, rust, etc), but they aren't written in C. These should be listed...somewhere...but maybe that should wait until after the rearchitecture of the SDK...
- Using Rust with the Kubos SDK
	- Need regular cargo instructions. particularly regarding the target names and recommending building for release (rather than debug)
	- arm-linux-strip

Kubos Mission Applications
- Needs to be massively expanded to not just be a high level overview. There will be a different issue to specifically address this. The short version: What is this thing and how do I use it?

Kubos Services
- Core Services
	- Create overview pages for each of the core services and then link to their Rust API doc (don't need to do a full user guide for now)
- Hardware Services
	- Update with the available hardware services. Maybe give example queries/mutations
		- Hardware services could be broken out, each with their own page, but we're not doing full user guides for the moment, so could probably just link to the Rust doc
			- Note: Going forward, I want to expand the docs to go a little more in depth about what each query/mutation/return field is.
- Payload Services
	- Should be fine? Need to review the actual code and make sure it's still relevant and works
- GraphQL
	- Add examples/info for querying actual services/hardware
	- Code examples in each language (python, rust, c)

Kubos APIs
- Application API should get added to the index's list
- Device Interfaces
	- Update with all the new APIs. Link to their respective Rust API page
- Kubos HAL
	- Needs to get revisited... Can probably be reorganized by putting all the I2C APIs into a master 'I2C' folder. It's basically: Here's the I2C API you want depending on which language you're using.
		- Kubos Linux I2C API -> C API
	- CSP - Lives to see another day...

Kubos Linux
- General Guides
	- Add blurb about file transfer via ethernet
- SysAdmin Docs
	- Update list of Busybox commands
	- Device Tree Binary - Is there a website for help with device trees now? If there is, add it.
	- Resetting the Environment - It might be good if this was made more prominent somehow
	- New Doc: Configuring your System - How to update your configuration to include x,y,z hardware
		- menuconfig
		- config.toml
	- New Doc: Overview of the custom BR packages

Developer Docs
- Changelog - update it
- Kubos Device API Development
	- File Location - Fix the folder structure. We changed to the apis/services layout
	- Documentation - Add blurb about auto-generated Rust docs and how to reference them
	- Integration Tests - This is changing. Come to a conclusion about the new system and then update this.

**Comment by jacoffey3** [comment]
I think you can go to just docs.kubos.co/master/ 
Architecture: 

- Add Application Service/Registry
- Update overall view

Kubos SDK: 

- I think we should just refer people to the examples folder directly for now. There are docs on each example within that directory. I also want to pull out all of the examples that don't match what we are doing (for example - CSP). We should have a single main example for the payload/hardware service, with a note about a forthcoming mission application example. 

Kubos Mission Applications: 

- See above, and yes massively expanded. I don't think it'll land in this release though, but we should clearly indicate where the example will go when it's finished. 

Kubos Services - agree

Kubos APIs...specifically HAL:

- Agree with folder structure, I like that. 
- I think it's time to kill CSP. We have concrete examples that can be used instead, and we don't use it for anything. I think it's time to kill. 

Kubos Linux: Agree

Dev Docs: 

- Integration tests might not land in this release. I think it's a rabbit hole we can cover in the build up to the next release.

**Comment by jacoffey3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release Documentation Scoping](https://trello.com/c/LkMLW8DP/363-release-documentation-scoping)

**Comment by plauche** [comment]
Kubos Linux:
-  We should mention somewhere the need to properly power off the board and the risk of corruption if you don't
Misc:
- Get http://docs.kubos.com working
- Get our https://docs.kubos.com working - currently we can only serve up under http
