### ISSUE TITLE
404 in docs for https://docs.kubos.com/latest/services/communication.html

### ISSUE THREAD

**Issue by humphd** [kubos/kubos#339]
Reading through main page and docs, I notice that https://docs.kubos.com/1.14.0/services/communication.html is 404.  Its linked from https://www.kubos.com/kubos/ under Communications and the Explore button to https://docs.kubos.com/latest/services/communication.html.

I'm not sure where this issue belongs, apologies if there is a more logical place to file it.

**Comment by CatGarab** [comment]
Good catch! This is as good a place as any for this issue :smile:

**Comment by jacoffey3** [comment]
This is the correct place! We're just starting to encourage reporting here, hence the reason it's a bit barren.

**Comment by CatGarab** [comment]
The link has now been updated to point to our [communications framework](https://docs.kubos.com/latest/services/comms-framework.html) page
