### ISSUE TITLE
Kubos Docs Wishlist

### ISSUE THREAD

**Issue by CatGarab** [kubos/kubos#34]
At some point we'll spend some time customizing how our docs look (currently we just use the default ReadTheDocs theme with Sphinx). It's not a particularly high priority, so I don't think there's a card for it yet. And, if there was, I think it would just get buried since it's a longer term item. So I'm creating an issue to act as an ongoing wishlist for when we finally get around to it:

- Change the default TOC depth. It's set to 4. (Left-hand menu only goes 4 layers deep)
- Allow users to select which version of the docs they want to look at (1.0, 1.1, master, etc)
- Updated logo (main page and favicon)

**Comment by jacoffey3** [comment]
@CatGarab Did all of these get addressed with 1.3?

**Comment by CatGarab** [comment]
The TOC depth hasn't been addressed. The other two have.
