### ISSUE TITLE
App api and config.toml path

### ISSUE THREAD

**Issue by plauche** [kubos/kubos#361]
I noticed when attempting to run an example python application that it was crashing when looking for the `config.toml` in our default location. This location appears to be hardcoded in the `app_api` library. We may want to consider making this a configurable parameter in our applications. It is already configurable in our services, and it would be nice to run apps locally without recreating the `/home/system/etc` folder structure.

**Comment by CatGarab** [comment]
There's some similar problems with Rust apps, too: https://trello.com/c/NhcVpBhu/903-cant-pass-custom-config-file-to-a-rust-app

**Comment by jacoffey3** [comment]
@CatGarab @plauche is this still an issue?

**Comment by CatGarab** [comment]
It's addressed in the docs. Our tutorials show how to set up an app to allow a non-default config path to be given ([example](https://docs.kubos.com/1.19.0/tutorials/first-mission-app.html#querying-a-service))

If we consider this to be an adequate solution, then this issue can be closed
