### ISSUE TITLE
Minor Documentation Bug - Telemetry URL

### ISSUE THREAD

**Issue by daten** [kubos/kubos#501]
**Description**
I've been following the SDK tutorials end-to-end.  The "Fetching Telemetry Data" tutorial at https://docs.kubos.com/1.19.0/tutorials/querying-telemetry.html#graphiql includes an example URL with port 8050 which I believe should have been 8020 to match the current example local_config.toml from the github clone.

**System Details**
- Verified in SDK on Fedora Linux VM

**Severity**
- Mild 

**To Reproduce**
Documentation issue in this paragraph:

> Please navigate to http://0.0.0.0:8050/graphiql in order to communicate with the telemetry service for this tutorial. If you are using the SDK, replace 0.0.0.0 with the IP address you defined for your VM.

**Bug Output**
http://0.0.0.0:8050/graphiql

**Workaround**
http://0.0.0.0:8020/graphiql  (or in my case: http://127.0.0.1:8020/graphiql)

**Comment by daten** [comment]
Additionally, at the bottom of the tutorial, the example response is a duplicate of the input instead of the response.

The actual response should be:

**Comment by CatGarab** [comment]
Thanks for finding this! The tutorial will be updated in our next release :smile:
