### ISSUE TITLE
Minor Documentation Bug - Scheduling Tutorial, Missing description

### ISSUE THREAD

**Issue by daten** [kubos/kubos#502]
**Description**
On https://docs.kubos.com/1.19.0/tutorials/schedule-app.html#creating-and-importing-a-task-list and example command is given that is missing a required field.  A JSON file is constructed without a required "description" field, causing a latter command to fail.

**System Details**
- Verified with KubOS SDK on Fedora Linux VM

**Severity**
- Mild 

**To Reproduce**
> Create a new file called my-mission.json with the following contents:
```
{
    "tasks": [
        {
            "name": "my-app",
            "delay": "10s",
            "period": "10s",
            "app": {
                "name": "my-mission-app"
            }
        }
    ]
}
```
> Our import mutation should look like this:
```
mutation {
    importTaskList(name: "my-mission", path: "/home/user/kubos/my-mission.json", mode: "nominal") {
        success
        errors
    }
}
```

**Bug Output**
An error is returned from the importTaskList mutation about a missing "description" field in the JSON file.

**Workaround**
Add the missing field to the example file in the documentation.

**Comment by CatGarab** [comment]
Fixed with #505
